services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        network_mode: "service:gluetun"
        depends_on:
            gluetun:
                condition: service_healthy
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=${TZ}
            - WEBUI_PORT=8080
        volumes:
            - /home/joshua-kaisar/homelab/open80-homelab/qbittorrent/config:/config
            - /home/joshua-kaisar/homelab/open80-homelab/qbittorrent/data/torrents
