services:
    homeassistant1:
        container_name: 32-Raritian-Ave-homeAssistant
        image: ghcr.io/home-assistant/home-assistant:stable
        ports:
            - "8123:8123"
        volumes:
            - ${APPPATH}homeAssistant/32Raritan_config :/config
        restart: unless-stopped
        environment:
            - APPPATH=${APPPATH}

    # homeassistant2:
    #     container_name: homeassistant2
    #     image: ghcr.io/home-assistant/home-assistant:stable
    #     ports:
    #         - "8124:8123" # Maps internal 8123 to external 8124
    #     volumes:
    #         - ./ha2_config:/config
    #     restart: unless-stopped
