services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "1414:3000"  # Expose Grafana on port 3000
    environment:
      - GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - /home/joshua-kaisar/homelab/open80-homelab/grafana/data:/var/lib/grafana
    restart: unless-stopped