services:
    jellyfin:
        image: linuxserver/jellyfin
        container_name: jellyfin
        ports:
            - "8096:8096/tcp" # Jellyfin web interface
            - "7359:7359/udp" # Network discovery
            - "1900:1900/udp" # DLNA port
        volumes:
            - /home/joshua-kaisar/homelab/open80-homelab/jellyfin/config:/config
            - /home/joshua-kaisar/homelab/open80-homelab/jellyfin/cache:/cache
            - type: bind
              source: /mnt/nas/Movies
              target: /media/movies
            - type: bind
              source: /mnt/nas/Shows
              target: /media/shows
              read_only: true
        environment:
            - ARRPATH=${ARRPATH}
        restart: "unless-stopped"
