services:
    gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        ports:
            - "8888:8888/tcp" # Optional: HTTP proxy
            - "8388:8388/tcp" # Optional: Shadowsocks
            - "8388:8388/udp" # Optional: Shadowsocks
            - "8000:8000" # Control server for status widget
        volumes:
            - ./data:/gluetun
        environment:
            - VPN_SERVICE_PROVIDER=surfshark
            - VPN_TYPE=wireguard
            - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
            - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
            - TZ=${TZ}
            - UPDATER_PERIOD=24h
            - GLUETUN_CONTROL_SERVER_ADDRESS=:8000
