services:
    gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        ports:
            - "8888:8888/tcp" # Optional: HTTP proxy
            - "8388:8388/tcp" # Optional: Shadowsocks
            - "8388:8388/udp" # Optional: Shadowsocks
            - "18000:8000" # Use 18000 on the host instead of 8000 for Widget
        # volumes:
        #     - /home/joshua-kaisar/homelab/open80-homelab/gluetun/data:/gluetun
        environment:
            - VPN_SERVICE_PROVIDER=surfshark
            - VPN_TYPE=wireguard
            - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
            - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
            - TZ=${TZ}
            - SERVER_CITIES=New York
            - UPDATER_PERIOD=24h
            - GLUETUN_CONTROL_SERVER_ADDRESS=:8000
            - GLUETUN_CONTROL_SERVER_USER=
            - GLUETUN_CONTROL_SERVER_PASSWORD=
