- name: Open80
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
      - size: small
        widgets:
            - type: calendar
              first-day-of-week: monday

            - type: weather
              location: New York, United States
              units: imperial # alternatively "metric"
              hour-format: 12h # alternatively "24h"
              # Optionally hide the location from being displayed in the widget
              # hide-location: true

            - type: twitch-channels
              channels:
                  - theprimeagen
                  - j_blow
                  - piratesoftware
                  - cohhcarnage
                  - christitustech
                  - EJ_SA

      - size: full
        widgets:
            - type: custom-api
              title: Daily Bible Verse
              cache: 3h
              url: https://bible-api.com/data/web/random
              template: |
                  <p class="size-h2 color-highlight">{{ .JSON.String "random_verse.book" }} {{ .JSON.String "random_verse.chapter" }}:{{ .JSON.String "random_verse.verse" }}</p>
                  <p class="size-h4 color-paragraph">{{ .JSON.String "random_verse.text" }}</p>
            - type: group
              widgets:
                  - type: hacker-news
                  - type: lobsters

            - type: videos
              channels:
                  - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UCsBjURrPoezykLs9EqgamOA # Fireship
                  - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
                  - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

            - type: group
              widgets:
                  - type: reddit
                    subreddit: homelab
                    show-thumbnails: true
                  - type: reddit
                    subreddit: lemmino
                    show-thumbnails: true
      - size: small
        widgets:
            # - type: custom-api
            #   title: VPN status
            #   cache: 1m
            #   url: http://${GLUETUN_URL}/v1/publicip/ip
            #   headers:
            #       X-API-Key: ${GLUETUN_API_KEY}
            #   template: |
            #       {{ if eq .Response.StatusCode 200 }}
            #         {{ $ip := (.JSON.String "public_ip") }}
            #         {{ $city := (.JSON.String "city") }}
            #         {{ $country := (.JSON.String "country") }}
            #         {{ if eq $ip "" }}
            #           <div>
            #             <div>
            #               <div>
            #                 <div class="color-highlight size-h3">
            #                   Your VPN is not connected!
            #                   <span class="color-negative">●</span>
            #                 </div>
            #               </div>
            #             </div>
            #           </div>
            #         {{ else }}
            #           <div>
            #             <div>
            #               <div>
            #                 <div class="color-highlight size-h3">
            #                   Your VPN is connected!
            #                   <span class="color-positive">●</span>
            #                 </div>
            #               </div>
            #               <div class="size-h5">{{ $ip }} - {{ $city }}, {{ $country }}</div>
            #             </div>
            #           </div>
            #         {{ end }}
            #       {{ else }}
            #         <div style="text-align: center; color: var(--color-negative);">
            #           Error: {{ .Response.StatusCode }} - {{ .Response.Status }}
            #         </div>
            #       {{ end }}
            - type: markets
              markets:
                  - symbol: VOO
                    name: Vanguard S&P 500 ETF
                  - symbol: VTI
                    name: Vanguard Total Stock Market ETF
                  - symbol: QQQ
                    name: Invesco QQQ Trust
                  - symbol: BRK-B
                    name: Berkshire Hathaway
                  - symbol: SCHB
                    name: Schwab U.S. Broad Market ETF
                  - symbol: BTC-USD
                    name: Bitcoin

            - type: releases
              cache: 1d
              # Without authentication the Github API allows for up to 60 requests per hour. You can create a
              # read-only token from your Github account settings and use it here to increase the limit.
              # token: ...
              repositories:
                  - glanceapp/glance
                  - go-gitea/gitea
                  - immich-app/immich
                  - syncthing/syncthing
