- name: Startpage
  hide-desktop-navigation: false
  center-vertically: true
  columns:
      - size: small
        widgets:
            - type: repository
              repository: joshuakaisar/open80-homelab
              pull-requests-limit: 5
              issues-limit: 3
              commits-limit: 3
      - size: full
        widgets:
            - type: search
              autofocus: true
              search-engine: google
              new-tab: true
              bangs:
                  - title: YouTube
                    shortcut: "!yt"
                    url: https://www.youtube.com/results?search_query={QUERY}
                  - title: Github
                    shortcut: "!gh"
                    url: https://github.com/search?q={QUERY}&type=repositories
