services:
    glance:
        container_name: glance
        image: glanceapp/glance
        restart: unless-stopped
        volumes:
            - /home/joshua-kaisar/homelab/open80-homelab/glance/config:/app/config
            - /home/joshua-kaisar/homelab/open80-homelab/glance/assets/:/app/assets
            # Optionally, enable Docker containers widget
            # - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            - QBITTORRENT_URL=${QBITTORRENT_URL}
            - RADARR_URL=${RADARR_URL}
            - SONARR_URL=${SONARR_URL}
            - PROWLARR_URL=${PROWLARR_URL}
            - HOMARR_URL=${HOMARR_URL}
            - LIDARR_URL=${LIDARR_URL}
            - RADARR_URL=${RADARR_URL}
        networks:
            - nginxproxymanager_default # Connect to NPM's network

networks:
    nginxproxymanager_default:
        external: true
