services:
    glance:
        container_name: glance
        image: glanceapp/glance
        restart: unless-stopped
        volumes:
            - ./glance/config/glance.yml:/app/config/glance.yml
            - ./glance/assets/:/app/assets
            # Optionally, also mount docker socket if you want to use the docker containers widget
            # - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 3000:3000
        env_file: .env
