services:
    gluetun:
        image: qmcgaw/gluetun:latest
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        ports:
            - 8080:8080
            - 6881:6881
            - 6881:6881/udp
        volumes:
            - /home/joshua-kaisar/homelab/open80-homelab/qbittorrentVPN/gluetun/data:/gluetun
        environment:
            - VPN_SERVICE_PROVIDER=surfshark
            - VPN_TYPE=wireguard
            - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
            - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
            - TZ=${TZ}
            - SERVER_CITIES=${SERVER_CITIES}
            - UPDATER_PERIOD=${UPDATER_PERIOD}
            - GLUETUN_CONTROL_SERVER_ADDRESS=:8000

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        network_mode: "service:gluetun"
        depends_on:
            gluetun:
                condition: service_healthy
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=${TZ}
            - WEBUI_PORT=8080
        volumes:
            - /home/joshua-kaisar/homelab/open80-homelab/qbittorrentVPN/qbittorrent/config:/config
            - /home/joshua-kaisar/homelab/open80-homelab/qbittorrentVPN/qbittorrent/data/torrents:/data/torrents
