# https://www.reddit.com/r/selfhosted/comments/15oe631/gluetun_and_qbittorrent_correct_setup_in/
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/joshua-kaisar/homelab/open80-homelab/qbittorrentVPN/qbittorrent/config:/config
      - /home/joshua-kaisar/homelab/open80-homelab/arrStack/data/Downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    ports:
      # - 9696:9696 #prowlarr
      # - 7878:7878 #radarr
      # - 8989:8989 #sonarr
      # - 6767:6767 #bazarr
      # - 8686:8686 #lidarr
      # - 8787:8787 #readarr
      - 8080:8080 #qbittorrent
      - 6881:6881 #qbittorrent
      - 6881:6881/udp #qbittorrent
      - 4040:8000 #gluetun control server
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - TZ=${TZ}
      - SERVER_CITIES=${SERVER_CITIES}
      - UPDATER_PERIOD=${UPDATER_PERIOD}
      # - GLUETUN_CONTROL_SERVER_ADDRESS=:8000
